export const products = [
  {
    id: "1",
    name: "Calculus Textbook",
    category: "Books",
    price: 45.99,
    seller: "John D.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: true,
    description:
      "Calculus: Early Transcendentals, 8th Edition. Perfect condition with minimal highlighting. Used for one semester only.",
    condition: "Like New",
    brand: "Pearson",
    location: "North Campus",
    postedDate: "3 days ago",
  },
  {
    id: "2",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    seller: "Sarah M.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: false,
    description:
      "Noise-cancelling wireless headphones with 30-hour battery life. Includes original packaging and accessories.",
    condition: "Good",
    brand: "Sony",
    location: "East Campus",
    postedDate: "1 week ago",
  },
  {
    id: "3",
    name: "Desk Lamp",
    category: "Furniture",
    price: 24.99,
    seller: "Mike T.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: false,
    description: "Adjustable LED desk lamp with multiple brightness settings and USB charging port.",
    condition: "Excellent",
    brand: "OttLite",
    location: "West Dorms",
    postedDate: "5 days ago",
  },
  {
    id: "4",
    name: "Backpack",
    category: "Accessories",
    price: 39.99,
    seller: "Emma L.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: true,
    description: "Durable backpack with laptop compartment, water bottle pockets, and multiple storage sections.",
    condition: "Like New",
    brand: "North Face",
    location: "Student Center",
    postedDate: "1 day ago",
  },
  {
    id: "5",
    name: "Chemistry Lab Kit",
    category: "Academic",
    price: 89.99,
    seller: "David K.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: false,
    description: "Complete chemistry lab kit with glassware, chemicals, and instruction manual. Perfect for Chem 101.",
    condition: "Good",
    brand: "LabMaster",
    location: "Science Building",
    postedDate: "2 weeks ago",
  },
  {
    id: "6",
    name: "Dorm Room Mini Fridge",
    category: "Appliances",
    price: 129.99,
    seller: "Lisa R.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: false,
    description:
      "Compact 3.2 cubic feet mini refrigerator, perfect for dorm rooms. Energy efficient with freezer compartment.",
    condition: "Good",
    brand: "Frigidaire",
    location: "South Dorms",
    postedDate: "3 weeks ago",
  },
  {
    id: "7",
    name: "Graphic Calculator",
    category: "Electronics",
    price: 119.99,
    seller: "Tom B.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: true,
    description:
      "TI-84 Plus graphing calculator. Required for most math and engineering courses. Includes manual and batteries.",
    condition: "Excellent",
    brand: "Texas Instruments",
    location: "Math Building",
    postedDate: "4 days ago",
  },
  {
    id: "8",
    name: "Ergonomic Chair",
    category: "Furniture",
    price: 149.99,
    seller: "Alex W.",
    image: "/placeholder.svg?height=400&width=400",
    isNew: false,
    description:
      "Adjustable ergonomic desk chair with lumbar support and breathable mesh back. Perfect for long study sessions.",
    condition: "Very Good",
    brand: "Herman Miller",
    location: "Off Campus",
    postedDate: "1 week ago",
  },
]

export const reviews = [
  {
    name: "Alex T.",
    date: "2 weeks ago",
    comment: "Great product! Exactly as described and arrived quickly.",
  },
  {
    name: "Jamie L.",
    date: "1 month ago",
    comment: "Good quality for the price. Would recommend to other students.",
  },
]

export const orders = [
  {
    id: "ORD-1234",
    date: "March 12, 2023",
    status: "Delivered",
    total: 125.98,
    items: [
      {
        name: "Calculus Textbook",
        price: 45.99,
        quantity: 1,
        image: "/placeholder.svg?height=64&width=64",
      },
      {
        name: "Wireless Headphones",
        price: 79.99,
        quantity: 1,
        image: "/placeholder.svg?height=64&width=64",
      },
    ],
  },
  {
    id: "ORD-5678",
    date: "February 28, 2023",
    status: "Processing",
    total: 39.99,
    items: [
      {
        name: "Backpack",
        price: 39.99,
        quantity: 1,
        image: "/placeholder.svg?height=64&width=64",
      },
    ],
  },
]

export const listings = [
  {
    id: "1",
    name: "Physics Textbook",
    category: "Books",
    price: 55.99,
    date: "March 15, 2023",
    status: "Active",
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: "2",
    name: "Desk Chair",
    category: "Furniture",
    price: 89.99,
    date: "March 10, 2023",
    status: "Pending",
    image: "/placeholder.svg?height=80&width=80",
  },
]
